services:
  gitea:
    image: docker.gitea.com/gitea:1.24.4-rootless
    restart: always
    networks: [gitea_net]
    volumes:
      - ./data:/var/lib/gitea
      - ./config:/etc/gitea
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
    environment:
      # Make internal URLs match what the runner/jobs will call
      GITEA__server__ROOT_URL: "http://gitea:3000/"
      # Provide a global Actions registration token at boot
      GITEA_RUNNER_REGISTRATION_TOKEN: "${GITEA_RUNNER_REGISTRATION_TOKEN}"
      # If you've already completed the install wizard, uncomment:
      # GITEA__security__INSTALL_LOCK: "true"
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:3000/api/v1/version >/dev/null 2>&1 || exit 1"]
      interval: 5s
      timeout: 3s
      retries: 30
    ports:
      - "3000:3000"
      - "2222:2222"

  act_runner:
    image: gitea/act_runner:latest
    depends_on:
      gitea:
        condition: service_healthy
    restart: always
    networks: [gitea_net]
    environment:
      GITEA_INSTANCE_URL: "http://gitea:3000"
      GITEA_RUNNER_REGISTRATION_TOKEN: "${GITEA_RUNNER_REGISTRATION_TOKEN}"
      GITEA_RUNNER_NAME: "docker_runner"
      CONFIG_FILE: "/config.yaml"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - runner_data:/data
      - ./runner/config.yaml:/config.yaml:ro

networks:
  gitea_net:
    name: gitea_net   # fixed name so runner/config.yaml can refer to it

volumes:
  runner_data:
